#!/bin/bash

# Agent PR 자동 생성 스크립트
# 사용법: ./create-agent-pr.sh <agent-name> <task-description>
# 예: ./create-agent-pr.sh planner "사용자 프로필 기능 기획"

set -e

AGENT=$1
TASK=$2

if [ -z "$AGENT" ] || [ -z "$TASK" ]; then
    echo "Usage: $0 <agent-name> <task-description>"
    echo "Example: $0 planner '사용자 프로필 기능 기획'"
    exit 1
fi

# Slack Webhook URL (환경변수 또는 직접 설정)
SLACK_WEBHOOK="${SLACK_WEBHOOK_URL:-}"

# Agent별 이모지 및 색상
case $AGENT in
    planner)
        EMOJI="📋"
        COLOR="#3498db"
        LABEL="agent:planner"
        ;;
    dba)
        EMOJI="🗄️"
        COLOR="#9b59b6"
        LABEL="agent:dba"
        ;;
    backend)
        EMOJI="⚙️"
        COLOR="#e74c3c"
        LABEL="agent:backend"
        ;;
    frontend)
        EMOJI="🎨"
        COLOR="#2ecc71"
        LABEL="agent:frontend"
        ;;
    controller)
        EMOJI="🤖"
        COLOR="#f39c12"
        LABEL="agent:controller"
        ;;
    *)
        EMOJI="🔧"
        COLOR="#95a5a6"
        LABEL="manual"
        ;;
esac

# 브랜치 이름 생성 (공백을 하이픈으로, 소문자 변환)
BRANCH_NAME="feature/${AGENT}-$(echo $TASK | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd '[:alnum:]-')"

echo "📦 Creating PR for $EMOJI $AGENT"
echo "📝 Task: $TASK"
echo "🌿 Branch: $BRANCH_NAME"

# 현재 브랜치 확인
CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# 이미 feature 브랜치가 아니라면 새 브랜치 생성
if [[ "$CURRENT_BRANCH" != feature/* ]]; then
    echo "🌿 Creating new branch: $BRANCH_NAME"
    git checkout -b "$BRANCH_NAME"
else
    echo "✅ Already on feature branch: $CURRENT_BRANCH"
    BRANCH_NAME=$CURRENT_BRANCH
fi

# 변경사항 확인
CHANGED_FILES=$(git diff --name-only master..HEAD 2>/dev/null || git diff --name-only main..HEAD 2>/dev/null || echo "")
CHANGED_FILES_COUNT=$(echo "$CHANGED_FILES" | grep -v '^$' | wc -l)

if [ "$CHANGED_FILES_COUNT" -eq 0 ]; then
    echo "⚠️  No changes detected"
    exit 0
fi

echo "📊 Files changed: $CHANGED_FILES_COUNT"

# Push (이미 push되어 있을 수 있음)
echo "⬆️  Pushing to remote..."
git push -u origin "$BRANCH_NAME" 2>/dev/null || echo "✅ Already pushed"

# PR Body 생성
BASE_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@' || echo "master")

DIFF_STAT=$(git diff --stat $BASE_BRANCH..HEAD 2>/dev/null || echo "")

PR_BODY="## $EMOJI Agent: $AGENT

### 📋 Task
$TASK

### 📊 Changes Summary
\`\`\`
$DIFF_STAT
\`\`\`

### 📝 Files Modified
\`\`\`
$CHANGED_FILES
\`\`\`

---
🤖 Auto-generated by Claude Agent System
"

# PR 생성
echo "🔨 Creating pull request..."

# gh CLI가 설치되어 있는지 확인
if ! command -v gh &> /dev/null; then
    echo "❌ GitHub CLI (gh) is not installed"
    echo "📦 Install: https://cli.github.com/"
    exit 1
fi

# gh CLI 인증 확인
if ! gh auth status &> /dev/null; then
    echo "❌ GitHub CLI is not authenticated"
    echo "🔑 Run: gh auth login"
    exit 1
fi

# PR 생성 (이미 존재할 수 있음)
PR_URL=$(gh pr create \
    --title "$EMOJI $AGENT: $TASK" \
    --body "$PR_BODY" \
    --base "$BASE_BRANCH" \
    --head "$BRANCH_NAME" \
    --label "$LABEL" \
    2>&1 | grep -oP 'https://[^\s]+' | head -1 || gh pr view --json url -q .url 2>/dev/null)

if [ -z "$PR_URL" ]; then
    echo "❌ Failed to create PR"
    exit 1
fi

echo "✅ PR created: $PR_URL"

# Slack 알림 (Webhook URL이 설정된 경우)
if [ -n "$SLACK_WEBHOOK" ]; then
    echo "📢 Sending Slack notification..."

    curl -X POST "$SLACK_WEBHOOK" \
        -H 'Content-Type: application/json' \
        -d "{
            \"attachments\": [{
                \"color\": \"$COLOR\",
                \"title\": \"$EMOJI New PR by $AGENT\",
                \"title_link\": \"$PR_URL\",
                \"fields\": [
                    {\"title\": \"Task\", \"value\": \"$TASK\", \"short\": false},
                    {\"title\": \"Branch\", \"value\": \"$BRANCH_NAME\", \"short\": true},
                    {\"title\": \"Files Changed\", \"value\": \"$CHANGED_FILES_COUNT\", \"short\": true}
                ],
                \"footer\": \"Claude Agent System\",
                \"ts\": $(date +%s)
            }]
        }" \
        --silent --output /dev/null

    echo "✅ Slack notification sent"
else
    echo "⚠️  SLACK_WEBHOOK_URL not set, skipping Slack notification"
fi

echo ""
echo "🎉 Done!"
echo "🔗 PR URL: $PR_URL"
